version: 2.0.{build}
image: Visual Studio 2017

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: nuget restore
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  
build_script:
- ps: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
test:
  assemblies:
    only:
    - DebugAttachHistory.Tests.dll
after_test:
- ps: Vsix-PushArtifacts | Vsix-PublishToGallery
