version: 2.4.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:  
  - ps: Vsix-IncrementVsixVersion -versionType revision | Vsix-UpdateBuildVersion
  
build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal

test:
  assemblies:
    only:
    - DebugAttachHistory.Tests.dll
    
after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
  
artifacts:
- path: DebugAttachHistory\bin\$(configuration)\DebugAttachHistory.vsix
  name: vsix

deploy:
  release: v$(appveyor_build_version)
  tag: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: Dqx4t5QD7f8InwqkfC8vs21KTkw7sYkqp4wJ5bGbp04/vDuZT4GjXx80GmOjR8MC
  artifact: vsix
  draft: false
  prerelease: true